// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHzJHj82NgofWxe1RRcfVtjlj71j4rfZY',
    appId: '1:181749183212:web:7d3033f024cf5aa9ff6bc9',
    messagingSenderId: '181749183212',
    projectId: 'chat-app-simple-302dd',
    authDomain: 'chat-app-simple-302dd.firebaseapp.com',
    storageBucket: 'chat-app-simple-302dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk2thGnEjpfTK_g4I7-Vl0Lw2QpKN5p_w',
    appId: '1:181749183212:android:ad440bc2ac49734fff6bc9',
    messagingSenderId: '181749183212',
    projectId: 'chat-app-simple-302dd',
    storageBucket: 'chat-app-simple-302dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0nQZ-hwKzRXBdWdsy7t6GiD1SFUncP-Q',
    appId: '1:181749183212:ios:94b4416d3ffcb72bff6bc9',
    messagingSenderId: '181749183212',
    projectId: 'chat-app-simple-302dd',
    storageBucket: 'chat-app-simple-302dd.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0nQZ-hwKzRXBdWdsy7t6GiD1SFUncP-Q',
    appId: '1:181749183212:ios:94b4416d3ffcb72bff6bc9',
    messagingSenderId: '181749183212',
    projectId: 'chat-app-simple-302dd',
    storageBucket: 'chat-app-simple-302dd.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHzJHj82NgofWxe1RRcfVtjlj71j4rfZY',
    appId: '1:181749183212:web:3b520a4ae11de2edff6bc9',
    messagingSenderId: '181749183212',
    projectId: 'chat-app-simple-302dd',
    authDomain: 'chat-app-simple-302dd.firebaseapp.com',
    storageBucket: 'chat-app-simple-302dd.firebasestorage.app',
  );
}
